### ISSUE TITLE
3D model

### ISSUE THREAD

**Issue by BozidarGrgurDrmic** [IvanVnucec/schroom#1]
Ne znam kako mogu otvoriti 3d model. Je li to uopće važno za mene? Ako da, koji program da skinem

P.S. Ovo šaljem također zato da se malo igram s githubom

**Comment by IvanVnucec** [comment]
Nije to vazno za tebe. Inace se to otvara sa Solidworks programom. Mozda ima i online neki emulator. 
Evo ti screen da vidis sto je do sada napravljeno.
![Screenshot_1](https://user-images.githubusercontent.com/50591550/62291802-20699e00-b465-11e9-989d-9b8a786c8e3d.png)


I da, otvori sebi "Bozidar" folder i neka unutra budu tvoje stvari za koje mislis da su vazne za projekt.
